# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'debb5d63-6c67-4d88-913f-25db92d2e701'
  imageRepository: 'react-demo'
  containerRegistry: 'dsrcaapp.azurecr.io'
  dockerfilePath: '**/zz_df'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: vmss
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'sc'
        appType: 'webAppContainer'
        WebAppName: 'reactappademo'
        deployToSlotOrASE: true
        ResourceGroupName: 'dsrca'
        SlotName: 'staging'
        DockerNamespace: 'dsrcaapp.azurecr.io'
        DockerRepository: 'react-demo'
        DockerImageTag: '$(tag)'
